- name: "install net tools through apt"
  hosts: docker-darkevil

  vars_prompt:
    - name: ansible_become_sudo
      prompt: "sudo password (deployer)"
      private: yes

  tasks:
    - name: "apt update"
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: "install net-tools"
      ansible.builtin.apt:
        name: net-tools
        state: present
      become: yes
